// Every tunable number in the game lives here (or in src/data/).

export const TILE_SIZE = 40;

export const LOOP = {
  FIXED_STEP: 1 / 60,
  MAX_STEPS_PER_FRAME: 5,
  MAX_FRAME_DT: 0.1,
};

export const CONTROLS = {
  UP: ['KeyW', 'ArrowUp'],
  DOWN: ['KeyS', 'ArrowDown'],
  LEFT: ['KeyA', 'ArrowLeft'],
  RIGHT: ['KeyD', 'ArrowRight'],
  RELOAD: ['KeyR'],
  MELEE: ['KeyV'],
  GRENADE: ['KeyG'],
  DECOY: ['KeyQ'],
  INTERACT: ['KeyE'],
  WEAPON_1: ['Digit1'],
  WEAPON_2: ['Digit2'],
  RESTART: ['Enter', 'Space'],
  SWITCH_MAP: ['KeyM'],
  FIRE_BUTTON: 0,
  MELEE_BUTTON: 2,
};

export const PLAYER = {
  RADIUS: 14,
  SPEED: 220,
  MAX_HEALTH: 100,
  REGEN_DELAY: 4,
  REGEN_RATE: 35,
  START_POINTS: 500,
  START_GRENADES: 2,
  MAX_GRENADES: 4,
  GRENADES_PER_ROUND: 2,
  START_DECOYS: 1,
  MAX_DECOYS: 2,
  DECOY_EVERY_N_ROUNDS: 3,
  MAX_WEAPONS: 2,
  INTERACT_RANGE: 70,
  AIM_LINE_LENGTH: 24,
  DAMAGE_FLASH_TIME: 0.3,
  THROW_COOLDOWN: 0.5,
};

export const MELEE = {
  RANGE: 52,
  ARC: Math.PI * 0.9,
  DAMAGE: 150,
  COOLDOWN: 0.65,
  SWING_TIME: 0.16,
};

export const ZOMBIE = {
  RADIUS: 14,
  HEAD_RADIUS: 6,
  BASE_HEALTH: 100,
  HEALTH_PER_ROUND: 60,
  LINEAR_HEALTH_ROUNDS: 9,
  HEALTH_GROWTH: 1.1,
  WALKER_SPEED: 74,
  WALKER_SPEED_PER_ROUND: 3,
  WALKER_MAX_SPEED: 115,
  RUNNER_SPEED: 150,
  RUNNER_SPEED_PER_ROUND: 3,
  RUNNER_MAX_SPEED: 185,
  ATTACK_REACH: 10,
  ATTACK_DAMAGE: 25,
  ATTACK_WINDUP: 0.4,
  ATTACK_LANDING_TOLERANCE: 1.3,
  ATTACK_COOLDOWN: 1.0,
  CLIMB_TIME: 1.6,
  HIT_FLASH_TIME: 0.12,
  SPEED_VARIANCE: 0.1,
  SEPARATION_ITERATIONS: 3,
  PLAYER_PUSH_SHARE: 0.25,
};

export const ROUNDS = {
  FIRST_ROUND_DELAY: 3,
  INTERMISSION: 6,
  ANNOUNCE_TIME: 3,
  BASE_COUNT: 6,
  COUNT_PER_ROUND: 3,
  COUNT_QUADRATIC: 0.1,
  MAX_ALIVE: 24,
  SPAWN_INTERVAL: 1.2,
  SPAWN_INTERVAL_DECAY: 0.05,
  MIN_SPAWN_INTERVAL: 0.4,
  RUNNER_START_ROUND: 4,
  RUNNER_SHARE_PER_ROUND: 0.06,
  RUNNER_MAX_SHARE: 0.5,
  WINDOW_SAME_AREA_WEIGHT: 4,
  WINDOW_DISTANCE_SOFTENING: 300,
};

export const POINTS = {
  HIT: 10,
  KILL: 50,
  HEADSHOT_KILL: 100,
  MELEE_KILL: 130,
};

export const COMBAT = {
  HEADSHOT_MULTIPLIER: 2,
  BULLET_SPEED: 1500,
  BULLET_MAX_DISTANCE: 1400,
  BULLET_RADIUS: 2,
  BULLET_RAY_STEP: 6,
  MUZZLE_OFFSET: 6,
};

export const EXPLOSION = {
  PLAYER_DAMAGE_FACTOR: 0.3,
  PLAYER_MAX_DAMAGE: 60,
  EDGE_DAMAGE_FRACTION: 0.35,
  RING_TIME: 0.4,
  PARTICLES: 28,
  SHAKE: 8,
};

export const GRENADE = {
  RADIUS: 6,
  FRICTION: 3,
  MIN_THROW_DISTANCE: 60,
  MAX_THROW_DISTANCE: 420,
  FUSE: 1.5,
  DAMAGE: 450,
  BLAST_RADIUS: 130,
  BOUNCE: 0.45,
};

export const DECOY = {
  RADIUS: 7,
  FRICTION: 3,
  MIN_THROW_DISTANCE: 60,
  MAX_THROW_DISTANCE: 380,
  SETTLE_SPEED: 12,
  DURATION: 6,
  DAMAGE: 300,
  BLAST_RADIUS: 110,
  PULSE_INTERVAL: 0.5,
  PULSE_RADIUS: 60,
  BOUNCE: 0.45,
};

export const ECONOMY = {
  CRATE_PRICE: 950,
  CRATE_SPIN_TIME: 2.5,
  CRATE_SPIN_TICK: 0.09,
  CRATE_OFFER_TIME: 8,
  CRATE_SPECIAL_WEIGHT: 2,
  WALL_BUY_REFILL_FACTOR: 0.5,
};

export const PATHFINDING = {
  RECALC_INTERVAL: 0.35,
};

export const FLOATERS = {
  LIFE: 0.9,
  RISE_SPEED: 45,
  SMALL_SIZE: 13,
  BIG_SIZE: 18,
  SPREAD: 10,
};

export const PARTICLES = {
  MAX: 600,
  BLOOD_COUNT: 5,
  BLOOD_SPEED: 120,
  BLOOD_LIFE: 0.45,
  HEADSHOT_COUNT: 14,
  HEADSHOT_SPEED: 180,
  HEADSHOT_LIFE: 0.5,
  DEATH_COUNT: 12,
  DEATH_SPEED: 90,
  DEATH_LIFE: 0.6,
  MUZZLE_COUNT: 3,
  MUZZLE_SPEED: 260,
  MUZZLE_LIFE: 0.08,
  EXPLOSION_SPEED: 320,
  EXPLOSION_LIFE: 0.55,
  DRAG: 4,
};

export const CAMERA = {
  SHAKE_DECAY: 14,
};

export const COLORS = {
  BACKGROUND: '#0b0d10',
  VOID: '#0f1114',
  WALL: '#4a4f5a',
  WALL_EDGE: '#5d6370',
  FLOOR_GRID: 'rgba(255,255,255,0.03)',
  FLOOR_BY_AREA: ['#2c3140', '#2b3a30', '#3a2f2f', '#2e3648', '#3b3729', '#352d3c', '#2a3a3a'],
  FLOOR_LOCKED_DIM: 'rgba(0,0,0,0.55)',
  WINDOW_FRAME: '#3a2a1c',
  WINDOW_PLANK: '#8a5a2b',
  DOOR_CLOSED: '#b2562f',
  DOOR_CLOSED_EDGE: '#e2803d',
  DOOR_OPEN: 'rgba(226,128,61,0.25)',
  DOOR_TEXT: '#ffe0c2',
  WALL_BUY_ICON: '#e8e8e8',
  WALL_BUY_OWNED: '#8fd18f',
  WALL_BUY_TEXT: '#ffffff',
  CRATE: '#7a5a2a',
  CRATE_EDGE: '#c89a4a',
  CRATE_SPIN: '#ffd25a',
  CRATE_TEXT: '#fff0c8',
  PLAYER: '#4fc3f7',
  PLAYER_OUTLINE: '#e3f7ff',
  PLAYER_AIM: '#ffffff',
  PLAYER_DAMAGE: 'rgba(255,60,60,0.55)',
  ZOMBIE_WALKER: '#6aa84f',
  ZOMBIE_WALKER_HEAD: '#3c6b2a',
  ZOMBIE_RUNNER: '#c0504d',
  ZOMBIE_RUNNER_HEAD: '#6d2323',
  ZOMBIE_WINDUP: '#ffd27f',
  ZOMBIE_FLASH: '#ffffff',
  ZOMBIE_HP_BACK: 'rgba(0,0,0,0.6)',
  ZOMBIE_HP: '#d9534f',
  BULLET: '#ffe28a',
  EXPLOSIVE_SHELL: '#ff8a3d',
  GRENADE: '#2f3b2f',
  GRENADE_FUSE: '#ffb347',
  DECOY: '#4dd0e1',
  DECOY_PULSE: 'rgba(77,208,225,0.5)',
  EXPLOSION_RING: 'rgba(255,170,60,0.8)',
  BLOOD: '#7a1f1f',
  HEADSHOT: '#ffe066',
  DEATH: '#3d5a2a',
  MUZZLE: '#fff3b0',
  MELEE_ARC: 'rgba(255,255,255,0.35)',
  HUD_TEXT: '#ffffff',
  HUD_DIM: 'rgba(255,255,255,0.6)',
  HUD_PANEL: 'rgba(0,0,0,0.45)',
  HEALTH: '#4caf50',
  HEALTH_LOW: '#e53935',
  HEALTH_BACK: 'rgba(255,255,255,0.15)',
  POINTS: '#ffd54f',
  FLOATER_HIT: '#ffffff',
  FLOATER_KILL: '#ffd54f',
  FLOATER_HEADSHOT: '#ffe066',
  FLOATER_MELEE: '#ff8a65',
  FLOATER_BAD: '#ef5350',
  ROUND_ANNOUNCE: '#ff5252',
  PROMPT_BACK: 'rgba(0,0,0,0.7)',
  OVERLAY: 'rgba(0,0,0,0.75)',
};

export const HUD = {
  MARGIN: 20,
  HEALTH_WIDTH: 240,
  HEALTH_HEIGHT: 16,
  LOW_HEALTH_FRACTION: 0.35,
  FONT: 'system-ui, -apple-system, Segoe UI, Roboto, sans-serif',
  FONT_SIZE: 16,
  FONT_SIZE_LARGE: 26,
  FONT_SIZE_TITLE: 64,
  PROMPT_Y_FRACTION: 0.72,
  ANNOUNCE_FADE: 0.6,
  WEAPON_PANEL_WIDTH: 260,
};
